export const REGISTER_CALLED = "REGISTRATION_CALLED";
export const REGISTER_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTER_FAILURE= "REGISTRATION_FAILURE";

export const LOGIN_CALLED = "LOGIN_CALLED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE= "LOGIN_FAILURE";

export const LOGOUT_CALLED = "LOGOUT_CALLED";
export const LOGOUT_DONE = "LOGOUT_DONE";

export const GET_ALL_TEACHERS_CALLED = "GET_ALL_TEACHERS_CALLED";
export const GET_ALL_TEACHERS_SUCCESS = "GET_ALL_TEACHERS_SUCCESS";
export const GET_ALL_TEACHERS_FAIL = "GET_ALL_TEACHERS_FAIL";